### ISSUE TITLE
CAS RN - SC Biological/Geological

### ISSUE THREAD

**Issue by Acobut** [HPDCollaborative/special-conditions-beta#2]
Hello,
In the builder, there is a big warning at the substance level mentioning "WARNING: if you have a CASRN, this is not a Special Condition substance". However, according to the Special Conditions guidance for Bio and Geo materials, it is admitted to add CAS RN.
In Geological materials, add CASRN if available. 
![image](https://user-images.githubusercontent.com/45801592/49828335-9e9ff580-fd59-11e8-81de-7ed08fc38d95.png)

In Biological materials, add CASRN to identify the cellulose 
![image](https://user-images.githubusercontent.com/45801592/49828311-8d56e900-fd59-11e8-96a7-67bc77542810.png)

**Comment by 19peaches** [comment]
Adding the ability to add CAS numbers in both instances are optional ie: the OR in the directive. We chose to utilize the SC:GeoMat and SC:Bio identifiers in the Builder.

**Comment by Acobut** [comment]
OK!
