### ISSUE TITLE
Disclaimer in SC Geo mat

### ISSUE THREAD

**Issue by Acobut** [HPDCollaborative/special-conditions-beta#3]
Hello,
Maybe you could add "Leave blank if no information available", in some SC substance fields. If you leave the fields blank, it will generate the disclaimer. If not blank, it won't.
Especially for Geological materials, in not mandatory field (toxic metals, radioactive, typical composition).

**Comment by 19peaches** [comment]
Required fields are marked with a red asterisk as they are throughout the builder. I think most people on the internet are familiar with the methodology. Adding more and more text to these items will create an even muddier experience than what exists already.

**Comment by Acobut** [comment]
OK
