### ISSUE TITLE
Other Material Notes / Substance Notes for Special Conditions

### ISSUE THREAD

**Issue by Acobut** [HPDCollaborative/special-conditions-beta#4]
Hello,
Maybe you could add a separator between the automatic sentence in material/substance notes for clarity purposes. At the moment, you have the generated sentence, for example "SpecialConditionApplied:GeologicalMaterial" without any separator afterwards. It can make reading difficult if there are additional comments in the notes. So it would apply to all the notes you can add.

**Comment by 19peaches** [comment]
there should be a space between, I'll check it out. Thanks.

**Comment by Acobut** [comment]
Yes, there is indeed a space. But a space can be a space in a sentence. I would recommend a point "." or anything you'd like. But this is my personal opinion!

**Comment by 19peaches** [comment]
I believe our internal spec for this requires the text to fall inline with the SC applied message but I'll double check it.

**Comment by 19peaches** [comment]
@Acobut 

BTW let me personally thank you for contributing to the beta process, we really appreciate it.

**Comment by 19peaches** [comment]
Ok ... this isn't specifically addressed so I've added a triple hyphen in between and that looks pretty good as a separator. Thanks for the heads up.
